
spring:
    application:
        name: AUTH-SERVICE

server:
    port: 9100

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://AdmUser:MagicaBula_2018@localhost:8761/eureka/

sicurezza:
    uri: /auth/**
    header: Authorization
    prefix: Bearer 
    expiration: {24*60*60}
    secret: JwtSecretKey

# ==============================================================
# = GestUser Properties  
# ==============================================================
gestuser:
  srvUrl: http://localhost:8019/utenti/cerca/userid/
  userId: ReadUser
  password: BimBumBam_2018

